# Generated by Django 5.0.3 on 2024-07-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableau_de_bord', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
