# Generated by Django 5.0.3 on 2024-07-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau_de_bord', '0004_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantité disponible', null=True),
        ),
    ]
