# Generated by Django 5.0.3 on 2024-07-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableau_de_bord', '0006_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
    ]
